house<-read.table("~/household_power_consumption.txt",nrows=1,header=TRUE,na.strings="?",sep=";")
house<-read.table("~/household_power_consumption.txt",skip=397+60*24*15,nrows=60*24*2,header=FALSE,na.strings="?",sep=";",col.names=y,colClasses=sapply(house,class))
house$index=c(1:2880)
par(mfrow=c(2,2))
plot(house$index, house$Global_active_power, xaxt="n",ylab="Global active power(kilowatts)",type="l",xlab="")
axis(1, at=c(0,1440,2880),labels=expression("Monday","Tuesday","Wednesday"))
plot(house$index, house$Voltage, xaxt="n",ylab="Voltage",type="l",xlab="datetime")
axis(1, at=c(0,1440,2880),labels=expression("Monday","Tuesday","Wednesday"))
plot(house$index, house$Sub_metering_1,type="l",,xlab="",ylab="Energy sub metering",xaxt="n",ylim=range(house$Sub_metering_3))
par(new=TRUE)
plot(house$index, house$Sub_metering_2,type="l",col="red",xlab="",ylab="Energy sub metering",xaxt="n",ylim=range(house$Sub_metering_3))
par(new=TRUE)
plot(house$index, house$Sub_metering_3,type="l",col="blue",xlab="",ylab="Energy sub metering",xaxt="n")
axis(1, at=c(0,1440,2880),labels=expression("Monday","Tuesday","Wednesday"))
legend("topleft",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c('black','red','blue'),lty=1,cex=0.50)
plot(house$index, house$Global_reactive_power, xaxt="n",ylab="Globa_reactive_power",type="l",xlab="datetime")
axis(1, at=c(0,1440,2880),labels=expression("Monday","Tuesday","Wednesday"))

